### ISSUE TITLE
Bump docker to v24.0.7 to resolve CVE dependabot alers

### ISSUE THREAD

**Issue by dkotik** [adrianbrad/psqldocker#14]
Dear friend,

Current `github.com/docker/docker v24.0.2` triggers a moderate vulnerability warning from Dependabot. I see that there are four automated pull requests that were already generated. Would you please take a look at them. It may be easier to batch-merge them altogether.

Thank you in advance!

**Comment by adrianbrad** [comment]
Hello @dkotik, thanks for the notice, everything is up to date now, feel free to fetch the latest version of the package:
`go get -u github.com/adrianbrad/psqldocker@latest `

**Comment by dkotik** [comment]
@adrianbrad supersweet! Thank you for quick response! Nothing beats a 0 CVE friday! :-)
